package jSokoban.Gui;

import jSokoban.Actores.Actores;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Interfaz Principal del VideoJuego
 *
 * @since 27-05-2016
 * @version 0.9
 * @author alejo
 * @author gaso
 */
public class Principal extends javax.swing.JFrame {

    private JLabel imagenFondo;

    /**
     * Constructor que inicializa la interfaz y todos sus componentes
     */
    public Principal() {
        initComponents();
        setResizable(false);
        setSize(728, 645);
        asignarFondo();
        setLocationRelativeTo(null);

    }

    /**
     * Configurar Imagen de Fondo Ventana
     */
    private void asignarFondo() {
        //setContentPane(new JLabel(new ImageIcon(this.getClass().getResource("../Imagenes/Menu/Principal1.png"))));
        imagenFondo = new JLabel();
        imagenFondo.setIcon(new ImageIcon(Principal.class.getResource("../Imagenes/Menu/fondoPrincipal.png")));
        imagenFondo.setSize(getSize());
        add(imagenFondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSalir = new javax.swing.JLabel();
        bJugar = new javax.swing.JLabel();
        bMapas = new javax.swing.JLabel();
        bPuntaje = new javax.swing.JLabel();
        bCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bSalir.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSokoban/Imagenes/Menu/btnSalir.png"))); // NOI18N
        bSalir.setToolTipText("Salir");
        bSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSalirMouseClicked(evt);
            }
        });
        getContentPane().add(bSalir);
        bSalir.setBounds(270, 410, 190, 70);

        bJugar.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSokoban/Imagenes/Menu/btnJugar.png"))); // NOI18N
        bJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJugarMouseClicked(evt);
            }
        });
        getContentPane().add(bJugar);
        bJugar.setBounds(270, 150, 190, 56);

        bMapas.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bMapas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSokoban/Imagenes/Menu/btnMapas.png"))); // NOI18N
        bMapas.setToolTipText("Mapas");
        bMapas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMapasMouseClicked(evt);
            }
        });
        getContentPane().add(bMapas);
        bMapas.setBounds(270, 210, 189, 56);

        bPuntaje.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bPuntaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSokoban/Imagenes/Menu/btnPuntajes.png"))); // NOI18N
        bPuntaje.setText("Puntajes");
        getContentPane().add(bPuntaje);
        bPuntaje.setBounds(270, 280, 190, 60);

        bCreditos.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jSokoban/Imagenes/Menu/btnCreditos_.png"))); // NOI18N
        bCreditos.setToolTipText("Creditos");
        getContentPane().add(bCreditos);
        bCreditos.setBounds(270, 340, 200, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_bSalirMouseClicked

    private void bJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJugarMouseClicked
        setVisible(false);
        PrepararPartida partida = new PrepararPartida();
        partida.setVisible(true);
    }//GEN-LAST:event_bJugarMouseClicked

    private void bMapasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMapasMouseClicked
        setVisible(false);
        GestionMapas mapas = new GestionMapas();
        mapas.setVisible(true);
    }//GEN-LAST:event_bMapasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bCreditos;
    private javax.swing.JLabel bJugar;
    private javax.swing.JLabel bMapas;
    private javax.swing.JLabel bPuntaje;
    private javax.swing.JLabel bSalir;
    // End of variables declaration//GEN-END:variables
}
